import { useEffect } from "react";
import Head from "next/head";
import { MongoClient } from "mongodb";

import { Fragment } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import image from "next/image";

import Card from "../components/ui/card";
import AllPost from "../components/posts/allposts";
import NavBar from "../components/layout/NavBar";
import Script from "next/script";

function HomePage(props) {
  const styles = "min-h-screen dark-background text-gray-100 font-sans";

  return (
    <Fragment>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Card>
          {props.posts.map((post) => (
            <AllPost posts={post} key={post.id} />
          ))}
        </Card>
      </div>
    </Fragment>
  );
}

export async function getServerSideProps() {
  // fetch data from an API
  const client = await MongoClient.connect(
    "mongodb://localhost/restful_blog_appv3",
    { useNewUrlParser: true, useUnifiedTopology: true }
  );
  const db = client.db();

  const blogsCollection = db.collection("blogs");

  const posts = await blogsCollection.find().sort({ created: -1 }).toArray();

  client.close();

  return {
    props: {
      posts: posts.map((posts) => ({
        title: posts.title,
        body: posts.body,
        image: posts.image[0] ? posts.image[0].url : null,
        imageUrl: posts.imageUrl ? posts.imageUrl : null,
        id: posts._id.toString(),
        created: posts.created.toDateString(),
      })),
    },
  };
}

export default HomePage;
